ez=str(input('Fuhren zahl, bitte: '))
print("Sie hat gefuhrt:  ",ez)
zz=(ez+ez)
#print("zz  ",zz)
dz=(zz+ez)
#print("dz  ", dz)
#print("dz   ",type(dz))
#print("zz   ",type(zz))
#print("ez   ",type(ez))
ez=int(ez)
#print(type(ez))
zz=int(zz)
#rint(type(zz))
dz=int(dz)
#print(type(dz))
print("Result = ", ez+zz+dz)